### ISSUE TITLE
Missing tags 2.19.0 and 2.19.1

### ISSUE THREAD

**Issue by nliviu** [mongoose-os-apps/empty#2]
mos version 2.19.0 or 2.19.1 fails to clone this repo:
```
$ mos clone https://github.com/moongose-os-apps/empty
Error: exit status 128
/src/common/ourgit/ourgit_shell.go:265: fatal: couldn't find remote ref 2.19.0

$ mos clone https://github.com/moongose-os-apps/empty
Error: exit status 128
/src/common/ourgit/ourgit_shell.go:265: fatal: couldn't find remote ref 2.19.1
```

**Comment by rojer** [comment]
thank you for reporting, added tags and added the repo to the list of apps to be tagged on mos release.

we used to tag all of mongoose-os-app/* but that's undesirable, some apps want to manage their release cycle on their own.
